name = "atupa"
main = "src/index.js"
compatibility_date = "2024-01-29"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "atupa-data"
database_id = "cdddc447-a636-4159-8b2d-b5c5ee776b78"